### ISSUE TITLE
Compilation failed when upgrading to 3.6.3 version 

### ISSUE THREAD

**Issue by gautric** [cescoffier/vertx-kubernetes-workshop#11]
Hi, 

when I upgrade to 3.6.3 vert.x version I have got this error.

```
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ compulsive-traders ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 5 source files to /Users/XXXXXXX/Source/git/vertx/vertx-kubernetes-workshop/compulsive-traders/target/classes
INFO: io.vertx.codegen.CodeGenProcessor - Loaded service_proxy_handler code generator 
INFO: io.vertx.codegen.CodeGenProcessor - Loaded service_proxy code generator 
INFO: io.vertx.codegen.CodeGenProcessor - Loaded sockjs_service_proxies code generator 
INFO: io.vertx.codegen.CodeGenProcessor - Loaded sockjs_service_proxies code generator 
INFO: io.vertx.codegen.CodeGenProcessor - Loaded cheatsheet code generator 
INFO: io.vertx.codegen.CodeGenProcessor - Loaded cheatsheet code generator 
INFO: io.vertx.codegen.CodeGenProcessor - Loaded data_object_converters code generator 
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/XXXXXXX/Source/git/vertx/vertx-kubernetes-workshop/compulsive-traders/src/main/java/io/vertx/workshop/trader/impl/RXCompulsiveTraderVerticle.java:[10,45] package io.vertx.workshop.portfolio.reactivex does not exist
[ERROR] /Users/XXXXXXX/Source/git/vertx/vertx-kubernetes-workshop/compulsive-traders/src/main/java/io/vertx/workshop/trader/impl/TraderUtils.java:[59,121] package io.vertx.workshop.portfolio.reactivex does not exist
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for vertx-kubernetes-workshop 1.0-SNAPSHOT:
[INFO] 
[INFO] vertx-kubernetes-workshop .......................... SUCCESS [  0.374 s]
[INFO] currency-3rdparty-service .......................... SUCCESS [ 10.047 s]
[INFO] quote-generator .................................... SUCCESS [  8.709 s]
[INFO] portfolio-service .................................. SUCCESS [ 12.086 s]
[INFO] audit-service ...................................... SUCCESS [  4.883 s]
[INFO] compulsive-traders ................................. FAILURE [  1.926 s]
[INFO] vertx-exercises .................................... SKIPPED
[INFO] microservices-exercises ............................ SKIPPED
[INFO] micro-trader-dashboard ............................. SKIPPED
[INFO] currency-service-proxy ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  38.477 s
[INFO] Finished at: 2019-03-04T12:43:45+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project compulsive-traders: Compilation failure: Compilation failure: 
[ERROR] /Users/XXXXXXX/Source/git/vertx/vertx-kubernetes-workshop/compulsive-traders/src/main/java/io/vertx/workshop/trader/impl/RXCompulsiveTraderVerticle.java:[10,45] package io.vertx.workshop.portfolio.reactivex does not exist
[ERROR] /Users/XXXXXXX/Source/git/vertx/vertx-kubernetes-workshop/compulsive-traders/src/main/java/io/vertx/workshop/trader/impl/TraderUtils.java:[59,121] package io.vertx.workshop.portfolio.reactivex does not exist
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :compulsive-traders
```

**Comment by cescoffier** [comment]
@gautric 
Add the following dependency to the root `pom.xml` or in the portfolio `pom.xml`:

```
<dependency>
    <groupId>io.vertx</groupId>
    <artifactId>vertx-rx-java2-gen</artifactId>
    <version>${vertx.version}</version>
</dependency>
```
